esphome:
  name: sensor_cuarto
  platform: ESP32
  board: nodemcu-32s
  includes:
    - ble_sensor.h
  libraries:
    - "ArduinoJSON@^6"
    - "ESP32 BLE Arduino@^1.0.1"

wifi:
  ssid: "WLAN_FS"
  password: "5Z7ZIhkiYNVVTksXG"

  manual_ip:
    static_ip: 192.168.51.11
    gateway: 192.168.51.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Cuarto Fallback Hotspot"
    password: "j71nJTYVXMK3"

captive_portal:

# Enable logging
logger:
  level: INFO
# Enable Home Assistant API
api:
  password: "Xjul1475&"

ota:
  password: "Xjul1475&"
  
mqtt:
  broker: 192.168.4.9
  username: mqtt_user
  password: Xjul1475&

sensor:
  - platform: custom
    lambda: |-
      auto ble_sensor = new BLESensor(15000);
      App.register_component(ble_sensor);
      return {ble_sensor};
  
    sensors:
      name: "BLE Custom Sensor"
