esphome:
  name: sensor_oficina
  platform: ESP32
  board: esp-wrover-kit
  includes:
    - ble_sensor.h

wifi:
  ssid: "PTYLOGS"
  password: "KK4lvcGtm8Szfvv"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Oficina Fallback Hotspot"
    password: "jvWCbh7NC2cb"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Xjul1475&"

ota:
  password: "Xjul1475&"

sensor:
  - platform: custom
    lambda: |-
      auto ble_sensor = new BLESensor();
      App.register_component(ble_sensor);
      return {ble_sensor};
  
    sensors:
      name: "BLE Sensor"